[package]
name = "solar_analytics"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
log = "0.4"
env_logger = "0.10"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
dotenv = "0.15.0"
clickhouse = "0.13.2"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.3"
refinery = "0.8.16"

