name: Build and publish with Nix

on:
  push:
    branches: ['main', 'nix']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with Nix
        run: nix build .#dockerImage --print-out-paths

      - name: Load Nix-built image into Docker
        run: docker load < $(nix build .#dockerImage --print-out-paths)

      - name: Set image tag
        id: set_tag
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SANITIZED_BRANCH_NAME=$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')
          TAG=${SANITIZED_BRANCH_NAME:-latest}
          if [ "$BRANCH_NAME" == "main" ]; then
            TAG="main,latest"
          fi
          echo "TAGS=${TAG}" >> $GITHUB_OUTPUT

      - name: Tag image
        run: |
          IMAGE_ID=$(docker images solar_analytics:flake --format "{{.ID}}")
          IFS=',' read -ra TAGS <<< "${{ steps.set_tag.outputs.TAGS }}"
          for tag in "${TAGS[@]}"; do
            echo "Tagging ${IMAGE_ID} as ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$tag"
            docker tag $IMAGE_ID ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$tag
          done

      - name: Push image
        run: |
          IFS=',' read -ra TAGS <<< "${{ steps.set_tag.outputs.TAGS }}"
          for tag in "${TAGS[@]}"; do
            echo "Pushing ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$tag"
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$tag
          done

