name: Backend Image Build & Publish

on:
  push:
    branches: ["main", "develop"]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Build package
        run: nix build ".#image"
      
      - id: repository
        name: Generate Registry String
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ env.REGISTRY}}/${{ github.repository }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Load and Push Image to GHCR
        run: |
          IMAGE_TAG=$([ "${{ github.ref }}" = "refs/heads/develop" ] && echo "develop" || echo "latest")
          # Load the image from Nix build result
          docker load < ./result
          # Get the image ID of the loaded image
          IMAGE_ID=$(docker images --format "{{.ID}}" | head -n 1)
          # Tag the image with the appropriate name
          docker tag $IMAGE_ID ${{ steps.repository.outputs.lowercase }}:$IMAGE_TAG
          # Push the image
          docker push ${{ steps.repository.outputs.lowercase }}:$IMAGE_TAG